#ifndef _vshaderVshader_h_
#define _vshaderVshader_h_


// Header generated from binary by WriteAsBinHeader()..
static const int vshaderVshaderLength = 90;
static const unsigned int vshaderVshader[vshaderVshaderLength]={
	0x20205356,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000012,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x02000000,
	0x237820E4,	0x00000000,	0x00E40100,	0x02015500,	0x2EF820E4,	0x00000000,	0x00E40100,	0x0202AA00,	0x2EF820E4,	0x00000000,
	0x00E40100,	0x0203FF00,	0x0EF800E4,	0x00000000,	0x00000000,	0x00010000,	0x00F801E4,	0x00000000,	0x00000000,	0x00020000,
	0x00F802E4,	0x00000000,	0x00000000,	0x00030000,	0x00F803E4,	0x00000000,	0x00000000,	0x05000000,	0x188004E4,	0x00000000,
	0x04000000,	0x02080000,	0x237821E4,	0x00000000,	0x04E40101,	0x02095500,	0x2EF821E4,	0x00000000,	0x04E40101,	0x020AAA00,
	0x2EF821E4,	0x00000000,	0x04E40101,	0x020BFF00,	0x0EF804E4,	0x00000000,	0x00000000,	0x05010000,	0x188004E4,	0x00000000,
	0x05000000,	0x020C0000,	0x237822E4,	0x00000000,	0x05E40102,	0x020D5500,	0x2EF822E4,	0x00000000,	0x05E40102,	0x020EAA00,
	0x2EF822E4,	0x00000000,	0x05E40102,	0x020FFF00,	0x0EF805E4,	0x00000000,	0x00000000,	0x00000000,	0x1E000000,	0x00000000,};

//checksum generated by simpleCheckSum()
static const unsigned int vshaderVshaderCheckSum = 62;

static const char* vshaderVshaderText = 
	"# Vertex shader code for fixed pipeline emulation\n"
	"# S3C6410 FIMG-3DSE v.1.5\n"
	"#\n"
	"# Copyright 2010 Tomasz Figa <tomasz.figa@gmail.com>\n"
	"#\n"
	"# This program is free software: you can redistribute it and/or modify\n"
	"# it under the terms of the GNU Lesser General Public License as published by\n"
	"# the Free Software Foundation, either version 3 of the License, or\n"
	"# (at your option) any later version.\n"
	"#\n"
	"# This program is distributed in the hope that it will be useful,\n"
	"# but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
	"# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
	"# GNU Lesser General Public License for more details.\n"
	"#\n"
	"# You should have received a copy of the GNU Lesser General Public License\n"
	"# along with this program.  If not, see <http://www.gnu.org/licenses/>.\n"
	"#\n"
	"\n"
	"# Vertex shader version\n"
	"vs_3_0\n"
	"\n"
	"# FIMG version >= 1.2\n"
	"fimg_version    0x01020000\n"
	"\n"
	"# Shader code\n"
	"label start\n"
	"    # Transform position by transformation matrix\n"
	"    mul r0.xyzw, c0.xyzw, v0.xxxx\n"
	"    mad r0.xyzw, c1.xyzw, v0.yyyy, r0.xyzw\n"
	"    mad r0.xyzw, c2.xyzw, v0.zzzz, r0.xyzw\n"
	"    mad o0.xyzw, c3.xyzw, v0.wwww, r0.xyzw\n"
	"\n"
	"    # Pass vertex normal\n"
	"    mov o1, v1\n"
	"\n"
	"    # Pass vertex color\n"
	"    mov o2, v2\n"
	"\n"
	"    # Pass vertex point size\n"
	"    mov o3, v3\n"
	"\n"
	"    # Skip if texture0 is disabled\n"
	"    bf notexture0, b0\n"
	"\n"
	"    # Transform texture0 coordinates\n"
	"    mul r1.xyzw, c8.xyzw,  v4.xxxx\n"
	"    mad r1.xyzw, c9.xyzw,  v4.yyyy, r1.xyzw\n"
	"    mad r1.xyzw, c10.xyzw, v4.zzzz, r1.xyzw\n"
	"    mad o4.xyzw, c11.xyzw, v4.wwww, r1.xyzw\n"
	"\n"
	"label notexture0\n"
	"    # Skip if texture1 is disabled\n"
	"    bf notexture1, b1\n"
	"\n"
	"    # Transform texture1 coordinates\n"
	"    mul r2.xyzw, c12.xyzw, v5.xxxx\n"
	"    mad r2.xyzw, c13.xyzw, v5.yyyy, r2.xyzw\n"
	"    mad r2.xyzw, c14.xyzw, v5.zzzz, r2.xyzw\n"
	"    mad o5.xyzw, c15.xyzw, v5.wwww, r2.xyzw\n"
	"\n"
	"label notexture1\n"
	"    # Return\n"
	"    ret\n"
	"# End of shader code\n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader vshaderVshaderShader(vshaderVshaderText, vshaderVshader, vshaderVshaderLength, vshaderVshaderCheckSum);


#endif


#endif //_vshaderVshader_h_
